server:
  port: 8083
springdoc:
  api-docs:
    #????????????????
    enabled: true
    #swagger????????????
    path: /api-docs
  swagger-ui:
    #??????swagger??????????????????http:127.0.0.1:8080/test??????????????swagger????
    path: /test
  #??????????
  packages-to-scan: com.example
  #????????????????????????????????????????????
  group-configs:
    #??????
    - group: admin
      #??????????
      pathsToMatch: /admin/**
      #??????
    - group: springDocSwagger3
      packages-to-scan: com.example

